version: "3.1"
services:
  mysql:
    image: mysql:5.7
    container_name: possessor-mysql
    volumes:
    - ./docker/mysql/data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=possessor
    - MYSQL_USER=possessor
    - MYSQL_PASSWORD=possessor
    ports:
    - "10006:3306"

  webserver:
    image: nginx:alpine
    container_name: possessor-webserver
    working_dir: /possessor
    volumes:
    - .:/possessor
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "10080:80"

  php-fpm:
    build: docker/php-fpm
    container_name: possessor-php-fpm
    working_dir: /possessor
    volumes:
    - .:/possessor
